<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- <link rel="stylesheet" href="css/style.css"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../styles/styles.css">
    <?php if (isset ($script)):?>
        <?= $script;?>
        <?php endif;?>
    <title><?php echo htmlspecialchars($h1title);  ?></title>
</head>
<header>
        <nav>
            <ul>
                <li><a href="admin.php">admin</a></li>
                <li><a href="home.php">home</a></li>
                <li><a href="sign_in.php">sign in</a></li>
                <li><a href="sign_up.php">sign up</a></li>
                <li><a href="add_article.php">add article</a></li>
            </ul>

        <?php if (isConnected()): ?>
            <div>
                <p class="greeting">Hello <?= htmlspecialchars($_SESSION['user']['firstname']);?> and welcome</p>
            </div>
            <a href="disconect.php" >
                <input type="submit" value="Se déconnecter">
            </a>
            </div>
        <?php endif; ?>
        </nav>
        <h1><?php echo htmlspecialchars($h1title);  ?></h1>
    </header>
    <?php
        include "../templates/".$template.'.phtml';
    
    
    
    ?>

</html>