<body>
    <main>
        <form method="POST" action="<?= buildUrl('edit_article', ['id'=>$article['idArt']]) ?>">
            <fieldset>
                <legend>Modifier un article</legend>
                <div>
                    <label for="title">Titre de l'article</label>
                    <input type="text" id="title" name="title" value="<?=$title;?>">
                    <?php if (isset($errors['title'])): ?>
                        <p class="error"><?=$errors['title'];?></p>
                    <?php endif; ?>
                </div>
                <div>
                    <label for="abstract">Résumé de l'article</label>
                    <textarea id="abstract" name="abstract"><?=$abstract;?></textarea>
                </div>
                <div>
                    <label for="content">Contenu de l'article</label>
                    <textarea id="content" name="content"><?=$content;?></textarea>
                    <?php if (isset($errors['content'])): ?>
                        <p class="error"><?=$errors['content'];?></p>
                    <?php endif; ?>
                </div>
                <div>
                    <label for="image">Image</label>
                    <input type="text" id="image" name="image" value="<?=$image;?>">
                </div>
                <input type="submit" value="Enregistrer">
            </fieldset>
        </form>

    </main>
</body>

